# Change these first
owner: ravpacheco # Your GitHub username
repo: od-status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: Portal
    url: https://portal.ouvidordigital.com.br
  - name: API - Ouvidor Digital
    url: https://us-central1-od-portal-hmg.cloudfunctions.net/getSpeakableProtocolNumber
  - name: Sites dos Canais
    url: https://ouvidordigital.com.br/od
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Secret Site
#   url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ouvidordigital.com.br
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /od-status-page
  # logoUrl: https://portal.ouvidordigital.com.br/assets/img/logo.svg
  logoUrl: https://od-check-protocol.web.app/images/logo.png
  name: Ouvidor Digital
  introTitle: "**Ouvidor Digital** fortalece a cultura ética nas organizações"
  introMessage: Página de disponibilidade dos serviços do [Ouvidor Digital](https://ouvidordigital.com) em **tempo real**.
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://ouvidordigital.com
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: Todos os sistemas estão funcionando corretamente
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentViewOnGitHub: View on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Status Atual
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response time (ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Todos os direitos reservados - [Ouvidor Digital](https://ouvidoridigital.com)
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
